blank_issues_enabled: false
contact_links:
  - name: 👨‍💻 Support
    url: "https://calendly.com/banky2000/30min"
    about: Get direct help from the author of this project
  - name: 🌟 Sponsor
    url: https://github.com/sponsors/bankole2000
    about: Like this project? Please consider supporting the author.